# Regression themes
# To include the pages in /_themes in the local build, run jekyll with the option
# --config _config.yml,_config_dev.yml,_themes.yml

# Define Jekyll collections
collections:
  themes:
    permalink: "/:collection/:path:output_ext"
    output: true
  theme_collection_1:
    permalink: "/:collection/:path:output_ext"
    output: true
  theme_collection_2:
    permalink: "/:collection/:path:output_ext"
    output: true
  theme_collection_3:
    permalink: "/:collection/:path:output_ext"
    output: true
  theme_collection_4:
    permalink: "/:collection/:path:output_ext"
    output: true
  theme_collection_4:
    permalink: "/:collection/:path:output_ext"
    output: true

just_the_docs:
  collections:
    themes:
      name: Themes
      nav_exclude: false
      nav_fold: true
      search_exclude: true
    theme_collection_1:
      name: Theme Default
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    theme_collection_2:
      name: Theme Layout
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    theme_collection_3:
      name: Theme Framework
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    theme_collection_4:
      name: Theme UI
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    theme_collection_5:
      name: Theme Components
      nav_exclude: false
      nav_fold: true
      search_exclude: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "theme"
    values:
      layout: "default"

# callouts_opacity: 0.15
# callouts_level: loud

callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  custom:
    title: Custom
    color: pink
    opacity: 0.3
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red
