# Regression tests
# To include the pages in /_tests in the local build, run jekyll with the option
# --config _config.yml,_config_dev.yml,_tests.yml

# Define Jekyll collections
collections:
  tests:
    permalink: "/:collection/:path:output_ext"
    output: true
  test_collection_1:
    permalink: "/:collection/:path:output_ext"
    output: true
  test_collection_2:
    permalink: "/:collection/:path:output_ext"
    output: true

ui_theme_doc:
  collections:
    tests:
      name: Tests
      nav_exclude: false
      nav_fold: true
      search_exclude: true
    test_collection_1:
      name: Test Collection 1
      nav_exclude: false
      nav_fold: true
      search_exclude: true
    test_collection_2:
      name: Test Collection 2
      nav_exclude: false
      nav_fold: true
      search_exclude: false


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "tests"
    values:
      layout: "default"

# callouts_opacity: 0.15
# callouts_level: loud

callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  custom:
    title: Custom
    color: pink
    opacity: 0.3
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red
